app:
  user:
    default:
      cipher-digit: 10
      day-max-send-count: 200
geetest:
  id: 43dd89d811fac495147fac164b7bc35e
  key: e6e7c653f658073aaff9bdebe7d7097b
  open: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: top.imzdx.qqmsg.model.po
qq:
  QQAPPID: 101970969
  QQAPPKEY: 22f8858b98c5b71d49aaa0ce761d172c
  back-url: https://push.imzdx.top/#/control
  redirect_uri: https%3A%2F%2Fpush.imzdx.top%2Fapi%2Fuser%2FqqLogin
server:
  port: 8000
spring:
  application:
    name: qqPush
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    password: renxing
    url: jdbc:mysql://localhost:3306/renxing_push?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: renxing
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev
