app:
  user:
    default:
      cipher-digit: 10
      day-max-send-count: 200
geetest:
  id: 43dd89d811fac495147fac164b7bc35e
  key: e6e7c653f658073aaff9bdebe7d7097b
  open: false
qq:
  QQAPPID: 101970969
  QQAPPKEY: 22f8858b98c5b71d49aaa0ce761d172c
  back-url: https://push.imzdx.top/#/control
  redirect_uri: https%3A%2F%2Fpush.imzdx.top%2Fapi%2Fuser%2FqqLogin
server:
  port: 8000
spring:
  application:
    name: renxing-push
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    password: renxing
    url: jdbc:mysql://localhost:3306/renxing_push?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: renxing
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #  因为暂时禁用了Swagger所以可以取消该注释
  #  mvc:
  #    pathmatch:
  #      matching-strategy: ant_path_matcher
  config:
    activate:
      on-profile: dev
